package net.yuan.nova.pis.entity;

public class PisAttachmentBlob {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.SUFFIX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String suffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT_BLOB.ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private byte[] attachment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.ID
     *
     * @return the value of PIS_ATTACHMENT_BLOB.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.ID
     *
     * @param id the value for PIS_ATTACHMENT_BLOB.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.MD5
     *
     * @return the value of PIS_ATTACHMENT_BLOB.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.MD5
     *
     * @param md5 the value for PIS_ATTACHMENT_BLOB.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.FILE_SIZE
     *
     * @return the value of PIS_ATTACHMENT_BLOB.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.FILE_SIZE
     *
     * @param fileSize the value for PIS_ATTACHMENT_BLOB.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.SUFFIX
     *
     * @return the value of PIS_ATTACHMENT_BLOB.SUFFIX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.SUFFIX
     *
     * @param suffix the value for PIS_ATTACHMENT_BLOB.SUFFIX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.PATH
     *
     * @return the value of PIS_ATTACHMENT_BLOB.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.PATH
     *
     * @param path the value for PIS_ATTACHMENT_BLOB.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT_BLOB.ATTACHMENT
     *
     * @return the value of PIS_ATTACHMENT_BLOB.ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public byte[] getAttachment() {
        return attachment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT_BLOB.ATTACHMENT
     *
     * @param attachment the value for PIS_ATTACHMENT_BLOB.ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setAttachment(byte[] attachment) {
        this.attachment = attachment;
    }
}