package net.yuan.nova.pis.entity;

import java.util.Date;

public class PisAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.ATTACHMENT_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.BLOBID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String blobid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.KINDID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String kindid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.KIND
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String kind;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String md5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.CREATOR
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.ATTACHMENT_ID
     *
     * @return the value of PIS_ATTACHMENT.ATTACHMENT_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.ATTACHMENT_ID
     *
     * @param attachmentId the value for PIS_ATTACHMENT.ATTACHMENT_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setAttachmentId(String attachmentId) {
        this.attachmentId = attachmentId == null ? null : attachmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.BLOBID
     *
     * @return the value of PIS_ATTACHMENT.BLOBID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getBlobid() {
        return blobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.BLOBID
     *
     * @param blobid the value for PIS_ATTACHMENT.BLOBID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setBlobid(String blobid) {
        this.blobid = blobid == null ? null : blobid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.KINDID
     *
     * @return the value of PIS_ATTACHMENT.KINDID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getKindid() {
        return kindid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.KINDID
     *
     * @param kindid the value for PIS_ATTACHMENT.KINDID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setKindid(String kindid) {
        this.kindid = kindid == null ? null : kindid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.KIND
     *
     * @return the value of PIS_ATTACHMENT.KIND
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getKind() {
        return kind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.KIND
     *
     * @param kind the value for PIS_ATTACHMENT.KIND
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setKind(String kind) {
        this.kind = kind == null ? null : kind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.NAME
     *
     * @return the value of PIS_ATTACHMENT.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.NAME
     *
     * @param name the value for PIS_ATTACHMENT.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.PATH
     *
     * @return the value of PIS_ATTACHMENT.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.PATH
     *
     * @param path the value for PIS_ATTACHMENT.PATH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.DESCRIPTION
     *
     * @return the value of PIS_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.DESCRIPTION
     *
     * @param description the value for PIS_ATTACHMENT.DESCRIPTION
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.TYPE
     *
     * @return the value of PIS_ATTACHMENT.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.TYPE
     *
     * @param type the value for PIS_ATTACHMENT.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.MD5
     *
     * @return the value of PIS_ATTACHMENT.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.MD5
     *
     * @param md5 the value for PIS_ATTACHMENT.MD5
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setMd5(String md5) {
        this.md5 = md5 == null ? null : md5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.FILE_SIZE
     *
     * @return the value of PIS_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.FILE_SIZE
     *
     * @param fileSize the value for PIS_ATTACHMENT.FILE_SIZE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.STATUS
     *
     * @return the value of PIS_ATTACHMENT.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.STATUS
     *
     * @param status the value for PIS_ATTACHMENT.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.CREATOR
     *
     * @return the value of PIS_ATTACHMENT.CREATOR
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.CREATOR
     *
     * @param creator the value for PIS_ATTACHMENT.CREATOR
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_ATTACHMENT.CREATE_TIME
     *
     * @return the value of PIS_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_ATTACHMENT.CREATE_TIME
     *
     * @param createTime the value for PIS_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}