package net.yuan.nova.pis.entity;

import java.util.Date;

public class PisCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.TEL
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.CITY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.PROPERTY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String property;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_CUSTOMER.APP_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date appTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.ID
     *
     * @return the value of PIS_CUSTOMER.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.ID
     *
     * @param id the value for PIS_CUSTOMER.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.NAME
     *
     * @return the value of PIS_CUSTOMER.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.NAME
     *
     * @param name the value for PIS_CUSTOMER.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.TEL
     *
     * @return the value of PIS_CUSTOMER.TEL
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.TEL
     *
     * @param tel the value for PIS_CUSTOMER.TEL
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.CITY
     *
     * @return the value of PIS_CUSTOMER.CITY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.CITY
     *
     * @param city the value for PIS_CUSTOMER.CITY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.PROPERTY
     *
     * @return the value of PIS_CUSTOMER.PROPERTY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getProperty() {
        return property;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.PROPERTY
     *
     * @param property the value for PIS_CUSTOMER.PROPERTY
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setProperty(String property) {
        this.property = property == null ? null : property.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_CUSTOMER.APP_TIME
     *
     * @return the value of PIS_CUSTOMER.APP_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_CUSTOMER.APP_TIME
     *
     * @param appTime the value for PIS_CUSTOMER.APP_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }
}