package net.yuan.nova.pis.entity;

import java.util.Date;

public class PisDevice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.DEVICE_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String deviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.USERID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.IMEI
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.DEVICE_NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String deviceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.CHANNEL_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.TOKEN
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_DEVICE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.DEVICE_ID
     *
     * @return the value of PIS_DEVICE.DEVICE_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.DEVICE_ID
     *
     * @param deviceId the value for PIS_DEVICE.DEVICE_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.USERID
     *
     * @return the value of PIS_DEVICE.USERID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.USERID
     *
     * @param userid the value for PIS_DEVICE.USERID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.IMEI
     *
     * @return the value of PIS_DEVICE.IMEI
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.IMEI
     *
     * @param imei the value for PIS_DEVICE.IMEI
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.DEVICE_NAME
     *
     * @return the value of PIS_DEVICE.DEVICE_NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getDeviceName() {
        return deviceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.DEVICE_NAME
     *
     * @param deviceName the value for PIS_DEVICE.DEVICE_NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setDeviceName(String deviceName) {
        this.deviceName = deviceName == null ? null : deviceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.CHANNEL_ID
     *
     * @return the value of PIS_DEVICE.CHANNEL_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.CHANNEL_ID
     *
     * @param channelId the value for PIS_DEVICE.CHANNEL_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.TOKEN
     *
     * @return the value of PIS_DEVICE.TOKEN
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.TOKEN
     *
     * @param token the value for PIS_DEVICE.TOKEN
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.TYPE
     *
     * @return the value of PIS_DEVICE.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.TYPE
     *
     * @param type the value for PIS_DEVICE.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.STATUS
     *
     * @return the value of PIS_DEVICE.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.STATUS
     *
     * @param status the value for PIS_DEVICE.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_DEVICE.CREATE_TIME
     *
     * @return the value of PIS_DEVICE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_DEVICE.CREATE_TIME
     *
     * @param createTime the value for PIS_DEVICE.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}