package net.yuan.nova.pis.entity;

import java.math.BigDecimal;
import java.util.Date;

public class PisProperty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String propertyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.PROPERTY_NAME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String propertyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.PROPERTY_TYPE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String propertyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.REAL_ESTATE_AGENCY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String realEstateAgency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.ADDRESS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.COUNTRY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.PROVINCE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.CITY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String city;
    private String cityTitle;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.COUNTY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.OPEN_DATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Date openDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.CHARACTERISTIC
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String characteristic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.DECORATION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String decoration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.AREA
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.YEARS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Integer years;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.GREEN_RATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private BigDecimal greenRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.PROPERTY_COMPANY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String propertyCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.DELIVERY_TIME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Date deliveryTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.AVG_PRICE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Integer avgPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.COMMISSION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private String commission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.RECOMMENDED_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Integer recommendedNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.RESERVATION_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Integer reservationNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_PROPERTY.VIEW_TIMES
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    private Integer viewTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.PROPERTY_ID
     *
     * @return the value of PIS_PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getPropertyId() {
        return propertyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.PROPERTY_ID
     *
     * @param propertyId the value for PIS_PROPERTY.PROPERTY_ID
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setPropertyId(String propertyId) {
        this.propertyId = propertyId == null ? null : propertyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.PROPERTY_NAME
     *
     * @return the value of PIS_PROPERTY.PROPERTY_NAME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.PROPERTY_NAME
     *
     * @param propertyName the value for PIS_PROPERTY.PROPERTY_NAME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName == null ? null : propertyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.PROPERTY_TYPE
     *
     * @return the value of PIS_PROPERTY.PROPERTY_TYPE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.PROPERTY_TYPE
     *
     * @param propertyType the value for PIS_PROPERTY.PROPERTY_TYPE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType == null ? null : propertyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.REAL_ESTATE_AGENCY
     *
     * @return the value of PIS_PROPERTY.REAL_ESTATE_AGENCY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getRealEstateAgency() {
        return realEstateAgency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.REAL_ESTATE_AGENCY
     *
     * @param realEstateAgency the value for PIS_PROPERTY.REAL_ESTATE_AGENCY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setRealEstateAgency(String realEstateAgency) {
        this.realEstateAgency = realEstateAgency == null ? null : realEstateAgency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.ADDRESS
     *
     * @return the value of PIS_PROPERTY.ADDRESS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.ADDRESS
     *
     * @param address the value for PIS_PROPERTY.ADDRESS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.COUNTRY
     *
     * @return the value of PIS_PROPERTY.COUNTRY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.COUNTRY
     *
     * @param country the value for PIS_PROPERTY.COUNTRY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.PROVINCE
     *
     * @return the value of PIS_PROPERTY.PROVINCE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.PROVINCE
     *
     * @param province the value for PIS_PROPERTY.PROVINCE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.CITY
     *
     * @return the value of PIS_PROPERTY.CITY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.CITY
     *
     * @param city the value for PIS_PROPERTY.CITY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.COUNTY
     *
     * @return the value of PIS_PROPERTY.COUNTY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.COUNTY
     *
     * @param county the value for PIS_PROPERTY.COUNTY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.OPEN_DATE
     *
     * @return the value of PIS_PROPERTY.OPEN_DATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Date getOpenDate() {
        return openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.OPEN_DATE
     *
     * @param openDate the value for PIS_PROPERTY.OPEN_DATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.CHARACTERISTIC
     *
     * @return the value of PIS_PROPERTY.CHARACTERISTIC
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getCharacteristic() {
        return characteristic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.CHARACTERISTIC
     *
     * @param characteristic the value for PIS_PROPERTY.CHARACTERISTIC
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setCharacteristic(String characteristic) {
        this.characteristic = characteristic == null ? null : characteristic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.DECORATION
     *
     * @return the value of PIS_PROPERTY.DECORATION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getDecoration() {
        return decoration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.DECORATION
     *
     * @param decoration the value for PIS_PROPERTY.DECORATION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setDecoration(String decoration) {
        this.decoration = decoration == null ? null : decoration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.AREA
     *
     * @return the value of PIS_PROPERTY.AREA
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.AREA
     *
     * @param area the value for PIS_PROPERTY.AREA
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.YEARS
     *
     * @return the value of PIS_PROPERTY.YEARS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Integer getYears() {
        return years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.YEARS
     *
     * @param years the value for PIS_PROPERTY.YEARS
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setYears(Integer years) {
        this.years = years;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.GREEN_RATE
     *
     * @return the value of PIS_PROPERTY.GREEN_RATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public BigDecimal getGreenRate() {
        return greenRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.GREEN_RATE
     *
     * @param greenRate the value for PIS_PROPERTY.GREEN_RATE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setGreenRate(BigDecimal greenRate) {
        this.greenRate = greenRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.PROPERTY_COMPANY
     *
     * @return the value of PIS_PROPERTY.PROPERTY_COMPANY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getPropertyCompany() {
        return propertyCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.PROPERTY_COMPANY
     *
     * @param propertyCompany the value for PIS_PROPERTY.PROPERTY_COMPANY
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setPropertyCompany(String propertyCompany) {
        this.propertyCompany = propertyCompany == null ? null : propertyCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.DELIVERY_TIME
     *
     * @return the value of PIS_PROPERTY.DELIVERY_TIME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Date getDeliveryTime() {
        return deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.DELIVERY_TIME
     *
     * @param deliveryTime the value for PIS_PROPERTY.DELIVERY_TIME
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setDeliveryTime(Date deliveryTime) {
        this.deliveryTime = deliveryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.AVG_PRICE
     *
     * @return the value of PIS_PROPERTY.AVG_PRICE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Integer getAvgPrice() {
        return avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.AVG_PRICE
     *
     * @param avgPrice the value for PIS_PROPERTY.AVG_PRICE
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setAvgPrice(Integer avgPrice) {
        this.avgPrice = avgPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.COMMISSION
     *
     * @return the value of PIS_PROPERTY.COMMISSION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public String getCommission() {
        return commission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.COMMISSION
     *
     * @param commission the value for PIS_PROPERTY.COMMISSION
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setCommission(String commission) {
        this.commission = commission == null ? null : commission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.RECOMMENDED_NUMBER
     *
     * @return the value of PIS_PROPERTY.RECOMMENDED_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Integer getRecommendedNumber() {
        return recommendedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.RECOMMENDED_NUMBER
     *
     * @param recommendedNumber the value for PIS_PROPERTY.RECOMMENDED_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setRecommendedNumber(Integer recommendedNumber) {
        this.recommendedNumber = recommendedNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.RESERVATION_NUMBER
     *
     * @return the value of PIS_PROPERTY.RESERVATION_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Integer getReservationNumber() {
        return reservationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.RESERVATION_NUMBER
     *
     * @param reservationNumber the value for PIS_PROPERTY.RESERVATION_NUMBER
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setReservationNumber(Integer reservationNumber) {
        this.reservationNumber = reservationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_PROPERTY.VIEW_TIMES
     *
     * @return the value of PIS_PROPERTY.VIEW_TIMES
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public Integer getViewTimes() {
        return viewTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_PROPERTY.VIEW_TIMES
     *
     * @param viewTimes the value for PIS_PROPERTY.VIEW_TIMES
     *
     * @mbggenerated Wed Apr 06 22:39:45 CST 2016
     */
    public void setViewTimes(Integer viewTimes) {
        this.viewTimes = viewTimes;
    }

	public String getCityTitle() {
		return cityTitle;
	}

	public void setCityTitle(String cityTitle) {
		this.cityTitle = cityTitle;
	}
    
}