package net.yuan.nova.pis.entity;

public class PisUserGroupShipKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP_SHIP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP_SHIP.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP_SHIP.GROUP_ID
     *
     * @return the value of PIS_USER_GROUP_SHIP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP_SHIP.GROUP_ID
     *
     * @param groupId the value for PIS_USER_GROUP_SHIP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP_SHIP.USER_ID
     *
     * @return the value of PIS_USER_GROUP_SHIP.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP_SHIP.USER_ID
     *
     * @param userId the value for PIS_USER_GROUP_SHIP.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }
}