package net.yuan.nova.pis.entity;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;

/**
 * 
 * <ul>
 * <li>app管理员</li>
 * <li>驻场专员</li>
 * <li>渠道经理</li>
 * <li>经纪公司</li>
 * <li>业务员</li>
 * </ul>
 * @author Administrator
 *
 */
public class PisUserGroup {
	//四种类型
	public static enum TYPE {
		// 管理员
		appAdmin,
		// 驻场专员
		commissioner,
		//渠道经理
		channelManager,
		// 经纪公司
		brokingFirm,
		//业务员
		salesman
	}

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.FATHER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String fatherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.INTRO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_GROUP.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.GROUP_ID
     *
     * @return the value of PIS_USER_GROUP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.GROUP_ID
     *
     * @param groupId the value for PIS_USER_GROUP.GROUP_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.FATHER_ID
     *
     * @return the value of PIS_USER_GROUP.FATHER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getFatherId() {
        return fatherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.FATHER_ID
     *
     * @param fatherId the value for PIS_USER_GROUP.FATHER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setFatherId(String fatherId) {
        this.fatherId = fatherId == null ? null : fatherId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.NAME
     *
     * @return the value of PIS_USER_GROUP.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.NAME
     *
     * @param name the value for PIS_USER_GROUP.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.TYPE
     *
     * @return the value of PIS_USER_GROUP.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.TYPE
     *
     * @param type the value for PIS_USER_GROUP.TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.INTRO
     *
     * @return the value of PIS_USER_GROUP.INTRO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.INTRO
     *
     * @param intro the value for PIS_USER_GROUP.INTRO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_GROUP.CREATE_TIME
     *
     * @return the value of PIS_USER_GROUP.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_GROUP.CREATE_TIME
     *
     * @param createTime the value for PIS_USER_GROUP.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    /**
     * 得到类型的描述
     * @return
     */
    public String getTypeTitle(){
    	switch (TYPE.valueOf(this.type)){
    	case appAdmin:
    		return "APP管理员";
    	case brokingFirm:
    		return "经纪公司";
    	case salesman:
    		return "业务员";
    	case commissioner:
    		return "案场专员";
    	case  channelManager:
    		return "渠道经理";
    	default:
    		return "未知类型:" + this.type;
    	}
    }
}