package net.yuan.nova.pis.entity;

import java.util.Date;

public class PisUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.ID_NUMBER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.SEX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.ADDRESS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.FRONT_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String frontPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.BACK_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String backPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.HOLD_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String holdPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_INFO.STATUS_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date statusTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.USER_ID
     *
     * @return the value of PIS_USER_INFO.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.USER_ID
     *
     * @param userId the value for PIS_USER_INFO.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.ID_NUMBER
     *
     * @return the value of PIS_USER_INFO.ID_NUMBER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.ID_NUMBER
     *
     * @param idNumber the value for PIS_USER_INFO.ID_NUMBER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.NAME
     *
     * @return the value of PIS_USER_INFO.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.NAME
     *
     * @param name the value for PIS_USER_INFO.NAME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.SEX
     *
     * @return the value of PIS_USER_INFO.SEX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.SEX
     *
     * @param sex the value for PIS_USER_INFO.SEX
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.ADDRESS
     *
     * @return the value of PIS_USER_INFO.ADDRESS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.ADDRESS
     *
     * @param address the value for PIS_USER_INFO.ADDRESS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.FRONT_PHOTO
     *
     * @return the value of PIS_USER_INFO.FRONT_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getFrontPhoto() {
        return frontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.FRONT_PHOTO
     *
     * @param frontPhoto the value for PIS_USER_INFO.FRONT_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setFrontPhoto(String frontPhoto) {
        this.frontPhoto = frontPhoto == null ? null : frontPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.BACK_PHOTO
     *
     * @return the value of PIS_USER_INFO.BACK_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getBackPhoto() {
        return backPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.BACK_PHOTO
     *
     * @param backPhoto the value for PIS_USER_INFO.BACK_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setBackPhoto(String backPhoto) {
        this.backPhoto = backPhoto == null ? null : backPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.HOLD_PHOTO
     *
     * @return the value of PIS_USER_INFO.HOLD_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getHoldPhoto() {
        return holdPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.HOLD_PHOTO
     *
     * @param holdPhoto the value for PIS_USER_INFO.HOLD_PHOTO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setHoldPhoto(String holdPhoto) {
        this.holdPhoto = holdPhoto == null ? null : holdPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.STATUS
     *
     * @return the value of PIS_USER_INFO.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.STATUS
     *
     * @param status the value for PIS_USER_INFO.STATUS
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.CREATE_TIME
     *
     * @return the value of PIS_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.CREATE_TIME
     *
     * @param createTime the value for PIS_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_INFO.STATUS_TIME
     *
     * @return the value of PIS_USER_INFO.STATUS_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getStatusTime() {
        return statusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_INFO.STATUS_TIME
     *
     * @param statusTime the value for PIS_USER_INFO.STATUS_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setStatusTime(Date statusTime) {
        this.statusTime = statusTime;
    }
}