package net.yuan.nova.pis.entity;

import java.util.Date;

public class PisUserOauth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_OAUTH.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_OAUTH.OPEN_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String openId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_OAUTH.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_OAUTH.OAUTH_TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private String oauthType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PIS_USER_OAUTH.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_OAUTH.ID
     *
     * @return the value of PIS_USER_OAUTH.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_OAUTH.ID
     *
     * @param id the value for PIS_USER_OAUTH.ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_OAUTH.OPEN_ID
     *
     * @return the value of PIS_USER_OAUTH.OPEN_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_OAUTH.OPEN_ID
     *
     * @param openId the value for PIS_USER_OAUTH.OPEN_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_OAUTH.USER_ID
     *
     * @return the value of PIS_USER_OAUTH.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_OAUTH.USER_ID
     *
     * @param userId the value for PIS_USER_OAUTH.USER_ID
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_OAUTH.OAUTH_TYPE
     *
     * @return the value of PIS_USER_OAUTH.OAUTH_TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public String getOauthType() {
        return oauthType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_OAUTH.OAUTH_TYPE
     *
     * @param oauthType the value for PIS_USER_OAUTH.OAUTH_TYPE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setOauthType(String oauthType) {
        this.oauthType = oauthType == null ? null : oauthType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PIS_USER_OAUTH.CREATE_TIME
     *
     * @return the value of PIS_USER_OAUTH.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PIS_USER_OAUTH.CREATE_TIME
     *
     * @param createTime the value for PIS_USER_OAUTH.CREATE_TIME
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}