package net.yuan.nova.pis.dao;

import java.util.List;
import net.yuan.nova.pis.entity.PisArticle;
import org.springframework.stereotype.Repository;

@Repository
public interface PisArticleMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int insert(PisArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int insertSelective(PisArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	PisArticle selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int updateByPrimaryKeySelective(PisArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(PisArticle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PISP_ARTICLE
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int updateByPrimaryKey(PisArticle record);

	/**
	 * 查询文章列表
	 * 
	 * @return
	 */
	List<PisArticle> selectArticleList();
}