package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisAttachment;

@Repository
public interface PisAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisAttachment selectByPrimaryKey(String attachmentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisAttachment record);
    
    int deleteAttchmentByKind(String kindId);
}