package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisAttachmentBlob;

@Repository
public interface PisAttachmentBlobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisAttachmentBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisAttachmentBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisAttachmentBlob selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisAttachmentBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(PisAttachmentBlob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_ATTACHMENT_BLOB
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisAttachmentBlob record);
}