package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisCustomer;

@Repository
public interface PisCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisCustomer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_CUSTOMER
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisCustomer record);
}