package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisDevice;

@Repository
public interface PisDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisDevice selectByPrimaryKey(String deviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_DEVICE
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisDevice record);
}