package net.yuan.nova.pis.dao;

import java.util.List;

import net.yuan.nova.pis.entity.PisProperty;

import org.springframework.stereotype.Repository;

@Repository
public interface PisPropertyMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int deleteByPrimaryKey(String propertyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int insert(PisProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int insertSelective(PisProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	PisProperty selectByPrimaryKey(String propertyId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int updateByPrimaryKeySelective(PisProperty record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table PIS_PROPERTY
	 *
	 * @mbggenerated Wed Apr 06 22:39:45 CST 2016
	 */
	int updateByPrimaryKey(PisProperty record);

	/**
	 * 获得楼盘数据列表
	 * 
	 * @return
	 */
	List<PisProperty> selectPisProperties();
}