package net.yuan.nova.pis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisUserGroup;

@Repository
public interface PisUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisUserGroup selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisUserGroup record);
    List<PisUserGroup> selectByParentId(@Param("parentId") String parentId);
    PisUserGroup selectByGroupName(@Param("groupName") String groupName);
    PisUserGroup selectByType(@Param("type") String type);
}