package net.yuan.nova.pis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisUserGroupShipKey;

@Repository
public interface PisUserGroupShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP_SHIP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(PisUserGroupShipKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP_SHIP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisUserGroupShipKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_GROUP_SHIP
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisUserGroupShipKey record);
    List<PisUserGroupShipKey> getByUserId(@Param("userId") String userId);
    List<PisUserGroupShipKey> getByGroupId(@Param("groupId") String groupId);
}