package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisUserInfo;

@Repository
public interface PisUserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisUserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisUserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_INFO
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisUserInfo record);
}