package net.yuan.nova.pis.dao;

import org.springframework.stereotype.Repository;

import net.yuan.nova.pis.entity.PisUserOauth;

@Repository
public interface PisUserOauthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insert(PisUserOauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int insertSelective(PisUserOauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    PisUserOauth selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKeySelective(PisUserOauth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PIS_USER_OAUTH
     *
     * @mbggenerated Wed Mar 23 14:22:23 CST 2016
     */
    int updateByPrimaryKey(PisUserOauth record);
}